# Generated by Django 2.2 on 2020-12-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-is_active', '-hours', 'level'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('e', 'легкий'), ('m', 'средний'), ('h', 'продвинутый')], db_index=True, default='e', max_length=1),
        ),
    ]
