# Generated by Django 2.2.3 on 2020-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'verbose_name': 'Направление подготовки', 'verbose_name_plural': 'Направления подготовки'},
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='e', max_length=1),
        ),
    ]
