# Generated by Django 2.2.3 on 2020-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201024_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('e', 'легкий'), ('m', 'средний'), ('h', 'продвинутый')], default='e', max_length=1),
        ),
    ]
